name: test action
on:
  push:
    branches:
      - v1
      - v1-actions-test
  workflow_dispatch:

jobs:
  install:
    strategy:
      matrix:
        env:
          - runner: ubuntu-latest
          - runner: macos-latest
    name: test action
    runs-on: ${{ matrix.env.runner }}
    steps:
      - uses: fujiwara/lambroll@v1-actions-test
        with:
          version: v1.0.4
      - run: |
          lambroll version 2>&1 | fgrep v1.0.4
      - uses: fujiwara/lambroll@v1
        with:
          version: v1.0.5
      - run: |
          lambroll version 2>&1 | fgrep v1.0.5
      - uses: fujiwara/lambroll@v1-actions-test
        with:
          version-file: .test-lambroll-version
      - run: |
          lambroll version 2>&1 | fgrep v1.1.3
